"""add order status

Revision ID: 0043a0eaccda
Revises: 5ef5453c19e6
Create Date: 2020-07-15 19:10:58.059602

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0043a0eaccda"
down_revision = "5ef5453c19e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_status_update",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_status_update_id"), "order_status_update", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_status_update_id"), table_name="order_status_update")
    op.drop_table("order_status_update")
    # ### end Alembic commands ###
