"""empty message

Revision ID: 06e7ed82f1d3
Revises: e05f0fda0ffd
Create Date: 2020-07-16 00:01:50.458577

"""


# revision identifiers, used by Alembic.
revision = "06e7ed82f1d3"
down_revision = "e05f0fda0ffd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
