"""add order timestamp

Revision ID: 5ef5453c19e6
Revises: 4dfa4a93d27f
Create Date: 2020-07-15 17:32:16.719563

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5ef5453c19e6"
down_revision = "4dfa4a93d27f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("timestamp", sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "timestamp")
    # ### end Alembic commands ###
