"""remove toppings model

Revision ID: dde1007e7714
Revises: 0043a0eaccda
Create Date: 2020-07-15 20:45:10.873953

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "dde1007e7714"
down_revision = "0043a0eaccda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pizza_topping_id", table_name="pizza_topping")
    op.drop_table("pizza_topping")
    op.drop_index("ix_topping_id", table_name="topping")
    op.drop_index("ix_topping_name", table_name="topping")
    op.drop_table("topping")
    op.add_column(
        "pizza", sa.Column("data", postgresql.ARRAY(sa.Integer()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pizza", "data")
    op.create_table(
        "topping",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('topping_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="topping_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_topping_name", "topping", ["name"], unique=True)
    op.create_index("ix_topping_id", "topping", ["id"], unique=False)
    op.create_table(
        "pizza_topping",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("pizza_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("topping_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["pizza_id"], ["pizza.id"], name="pizza_topping_pizza_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["topping_id"], ["topping.id"], name="pizza_topping_topping_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="pizza_topping_pkey"),
    )
    op.create_index("ix_pizza_topping_id", "pizza_topping", ["id"], unique=False)
    # ### end Alembic commands ###
